font_size 13.0
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Bold
italic_font      JetBrainsMono Nerd Font Mono Italic
bold_italic_font JetBrainsMono Nerd Font Mono Bold Italic
symbol_map U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e300-U+e3e3,U+e5fa-U+e6b7,U+f000-U+fd46,U+f0001-U+f1af0 Symbols Nerd Font Mono
modify_font cell_width 115%
background_opacity 1.0
dynamic_background_opacity no
foreground              #00FF00
background              #000000
selection_foreground    #000000
selection_background    #FF007C
cursor                  #00FF88
cursor_text_color       #000000
cursor_shape            block
cursor_unfocused_hollow no
color0   #000000
color8   #444444
color1   #FF007C
color9   #FF3399
color2   #00FF00
color10  #39FF14
color3   #FFFF00
color11  #FFE600
color4   #00FFFF
color12  #33CCFF
color5   #FF007C
color13  #FF00AA
color6   #00FFFF
color14  #33FFFF
color7   #E0E0E0
color15  #FFFFFF
detect_urls no
allow_remote_control yes
listen_on unix:/tmp/kitty
map backspace send_text all \x08
#bold_font        auto
font_features    none
