background {
    monitor =
    path = ~/Pictures/catppuccin/landscapes/evening-sky.png
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(CBA6F7)
    inner_color = rgb(1E1E2E)
    font_color = rgb(CDD6F4)
    placeholder_text = <i>Password...</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(CDD6F4ff)
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}
