animations {
    enabled = true

    bezier = overshot,   0.05, 0.9, 0.1, 1.05
    bezier = smoothOut,  0.5,  0,   0.99, 0.99
    bezier = smoothIn,   0.5,  0,   0.68, 1.5
    bezier = slide,      0.25, 0.1, 0.25, 1.0
    bezier = expo,       0.16, 1,   0.3,  1

    animation = windows,          1, 5, overshot,  slide
    animation = windowsIn,        1, 5, overshot,  slide
    animation = windowsOut,       1, 4, smoothOut, slide
    animation = windowsMove,      1, 4, slide

    animation = border,           1, 10, default
    animation = borderangle,      1, 8,  linear,   loop

    animation = fade,             1, 5, smoothIn
    animation = fadeIn,           1, 5, smoothIn
    animation = fadeOut,          1, 5, smoothOut

    animation = workspaces,       1, 5, overshot,  slide
    animation = specialWorkspace, 1, 4, smoothOut, slidefadevert
}

decoration {
    rounding = 14

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = false
        noise = 0.01
        contrast = 0.89
        brightness = 0.82
    }

    shadow {
        enabled = true
        range = 24
        render_power = 3
        color = rgba(06061488)
        color_inactive = rgba(00000066)
    }
}

general {
    gaps_in  = 5
    gaps_out = 12
    border_size = 2
    col.active_border   = rgba(6363f1ff) rgba(06b6d4ff) 45deg
    col.inactive_border = rgba(1e293baa)
    layout = dwindle
}
